//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Features/Input/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""IsaacControl"",
            ""id"": ""7b64d766-3a0b-42a3-8a18-e952fc09db75"",
            ""actions"": [
                {
                    ""name"": ""HorizontalMove"",
                    ""type"": ""Button"",
                    ""id"": ""b4a2d5a9-888b-4b18-a550-857aebc55a87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HorizontalFireTear"",
                    ""type"": ""Button"",
                    ""id"": ""af871513-4eae-46a5-8c82-f7789797821d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""VerticalMove"",
                    ""type"": ""Button"",
                    ""id"": ""fa7a591f-5102-45fa-806b-c78f1e158509"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""VerticalFireTear"",
                    ""type"": ""Button"",
                    ""id"": ""7d2abce1-f93f-4ad9-ad95-b08c5ce790a9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseBomb"",
                    ""type"": ""Button"",
                    ""id"": ""09b8aa41-8699-47a6-8b6b-2285dd2ce2e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""e1f0e250-b5a6-49cb-aeb7-a47667e07da5"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7b5655a2-7cf6-4391-b2f8-f32869482d6f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""e0c6a813-bf45-4229-935e-6f1c126bc269"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""637ac04e-b3a2-4ba5-8061-87ba7565a14b"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7bf92998-dd0e-46dc-b210-5fce3cb741df"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""df750d24-cf93-48a5-b050-ec0f6cdccb97"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""0766e911-1d77-4d55-b339-d90a48d224f9"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalFireTear"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""757a3516-3085-4edf-ac91-e2e1ca803d41"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalFireTear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""144b4026-2a37-4bf9-8733-b2abd56493fc"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalFireTear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""a81a5aab-5d6d-41a0-8be9-7cffaef4cc2b"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalFireTear"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""4422409d-b7fc-414a-918c-89badc23fbd6"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalFireTear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""befbbfb3-4348-4752-a179-6359f1d6339a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalFireTear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""47dab541-e9e4-40b9-9482-507aec078710"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseBomb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // IsaacControl
        m_IsaacControl = asset.FindActionMap("IsaacControl", throwIfNotFound: true);
        m_IsaacControl_HorizontalMove = m_IsaacControl.FindAction("HorizontalMove", throwIfNotFound: true);
        m_IsaacControl_HorizontalFireTear = m_IsaacControl.FindAction("HorizontalFireTear", throwIfNotFound: true);
        m_IsaacControl_VerticalMove = m_IsaacControl.FindAction("VerticalMove", throwIfNotFound: true);
        m_IsaacControl_VerticalFireTear = m_IsaacControl.FindAction("VerticalFireTear", throwIfNotFound: true);
        m_IsaacControl_UseBomb = m_IsaacControl.FindAction("UseBomb", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // IsaacControl
    private readonly InputActionMap m_IsaacControl;
    private IIsaacControlActions m_IsaacControlActionsCallbackInterface;
    private readonly InputAction m_IsaacControl_HorizontalMove;
    private readonly InputAction m_IsaacControl_HorizontalFireTear;
    private readonly InputAction m_IsaacControl_VerticalMove;
    private readonly InputAction m_IsaacControl_VerticalFireTear;
    private readonly InputAction m_IsaacControl_UseBomb;
    public struct IsaacControlActions
    {
        private @Controls m_Wrapper;
        public IsaacControlActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @HorizontalMove => m_Wrapper.m_IsaacControl_HorizontalMove;
        public InputAction @HorizontalFireTear => m_Wrapper.m_IsaacControl_HorizontalFireTear;
        public InputAction @VerticalMove => m_Wrapper.m_IsaacControl_VerticalMove;
        public InputAction @VerticalFireTear => m_Wrapper.m_IsaacControl_VerticalFireTear;
        public InputAction @UseBomb => m_Wrapper.m_IsaacControl_UseBomb;
        public InputActionMap Get() { return m_Wrapper.m_IsaacControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(IsaacControlActions set) { return set.Get(); }
        public void SetCallbacks(IIsaacControlActions instance)
        {
            if (m_Wrapper.m_IsaacControlActionsCallbackInterface != null)
            {
                @HorizontalMove.started -= m_Wrapper.m_IsaacControlActionsCallbackInterface.OnHorizontalMove;
                @HorizontalMove.performed -= m_Wrapper.m_IsaacControlActionsCallbackInterface.OnHorizontalMove;
                @HorizontalMove.canceled -= m_Wrapper.m_IsaacControlActionsCallbackInterface.OnHorizontalMove;
                @HorizontalFireTear.started -= m_Wrapper.m_IsaacControlActionsCallbackInterface.OnHorizontalFireTear;
                @HorizontalFireTear.performed -= m_Wrapper.m_IsaacControlActionsCallbackInterface.OnHorizontalFireTear;
                @HorizontalFireTear.canceled -= m_Wrapper.m_IsaacControlActionsCallbackInterface.OnHorizontalFireTear;
                @VerticalMove.started -= m_Wrapper.m_IsaacControlActionsCallbackInterface.OnVerticalMove;
                @VerticalMove.performed -= m_Wrapper.m_IsaacControlActionsCallbackInterface.OnVerticalMove;
                @VerticalMove.canceled -= m_Wrapper.m_IsaacControlActionsCallbackInterface.OnVerticalMove;
                @VerticalFireTear.started -= m_Wrapper.m_IsaacControlActionsCallbackInterface.OnVerticalFireTear;
                @VerticalFireTear.performed -= m_Wrapper.m_IsaacControlActionsCallbackInterface.OnVerticalFireTear;
                @VerticalFireTear.canceled -= m_Wrapper.m_IsaacControlActionsCallbackInterface.OnVerticalFireTear;
                @UseBomb.started -= m_Wrapper.m_IsaacControlActionsCallbackInterface.OnUseBomb;
                @UseBomb.performed -= m_Wrapper.m_IsaacControlActionsCallbackInterface.OnUseBomb;
                @UseBomb.canceled -= m_Wrapper.m_IsaacControlActionsCallbackInterface.OnUseBomb;
            }
            m_Wrapper.m_IsaacControlActionsCallbackInterface = instance;
            if (instance != null)
            {
                @HorizontalMove.started += instance.OnHorizontalMove;
                @HorizontalMove.performed += instance.OnHorizontalMove;
                @HorizontalMove.canceled += instance.OnHorizontalMove;
                @HorizontalFireTear.started += instance.OnHorizontalFireTear;
                @HorizontalFireTear.performed += instance.OnHorizontalFireTear;
                @HorizontalFireTear.canceled += instance.OnHorizontalFireTear;
                @VerticalMove.started += instance.OnVerticalMove;
                @VerticalMove.performed += instance.OnVerticalMove;
                @VerticalMove.canceled += instance.OnVerticalMove;
                @VerticalFireTear.started += instance.OnVerticalFireTear;
                @VerticalFireTear.performed += instance.OnVerticalFireTear;
                @VerticalFireTear.canceled += instance.OnVerticalFireTear;
                @UseBomb.started += instance.OnUseBomb;
                @UseBomb.performed += instance.OnUseBomb;
                @UseBomb.canceled += instance.OnUseBomb;
            }
        }
    }
    public IsaacControlActions @IsaacControl => new IsaacControlActions(this);
    public interface IIsaacControlActions
    {
        void OnHorizontalMove(InputAction.CallbackContext context);
        void OnHorizontalFireTear(InputAction.CallbackContext context);
        void OnVerticalMove(InputAction.CallbackContext context);
        void OnVerticalFireTear(InputAction.CallbackContext context);
        void OnUseBomb(InputAction.CallbackContext context);
    }
}
